### ISSUE TITLE
Confusing type error

### ISSUE THREAD

**Issue by ckampfe** [sangria-graphql/sangria#171]
I'm not sure if this is the right place to post this. If not, I'll move it.

First, the error:

```
xcxk066$> ./gql.sc
Compiling gql.sc
gql.sc:90: type mismatch;
 found   : sangria.schema.Schema[Seq[$file.gql.UserRepo.User],$file.gql.UserRepo.User]
 required: sangria.schema.Schema[Seq[$file.gql.UserRepo.User],Any]
Note: $file.gql.UserRepo.User <: Any, but class Schema is invariant in type Val.
You may wish to define Val as +Val instead. (SLS 4.5)
              QuerySchema,
              ^
Compilation Failed
```

At the bottom is the code, an [ammonite](http://www.lihaoyi.com/Ammonite/) script I'm using to try to get a feel for Sangria. 

As you can see above, it fails to compile as written. If I do something dumb like cast `QuerySchema` to the `required` type signature (like `.asInstanceOf[Schema[Seq[User],Any]]`),
the program compiles and runs but blows up at runtime (in response to `xcxk066$> curl -XPOST "http://localhost:8080/?query="`:

(more after the stacktrace)

```
xcxk066$> ./gql.sc
Compiling gql.sc
Server listening on port 8080
schema {
  query: User
}

type User {
  name: String!
  age: Int!
}
java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to $file.gql$UserRepo$User
        at $file.gql$GqlData$$anonfun$1$$anonfun$apply$2.apply(gql.sc:36)
        at $file.gql$GqlData$$anonfun$1$$anonfun$apply$2.apply(gql.sc:36)
        at sangria.execution.Resolver.resolveField(Resolver.scala:813)
        at sangria.execution.Resolver$$anonfun$collectActionsPar$1.apply(Resolver.scala:363)
        at sangria.execution.Resolver$$anonfun$collectActionsPar$1.apply(Resolver.scala:357)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
```

I've read the docs and the scaladocs I'm pretty confused as to why the Schema appears to want an `Any`, or why `BoxedUnit` is appearing here. Seems like something is losing type information somewhere along the line but I'm not sure where/how. Any suggestions would be helpful. Thanks!

Code:
```
#!/usr/bin/env amm

import $ivy.`com.typesafe.akka::akka-http-experimental:2.4.11`
import $ivy.`org.sangria-graphql::sangria-circe:0.5.2`
import $ivy.`org.sangria-graphql::sangria:1.0.0-RC2`


object UserRepo {
  import sangria.macros.derive.GraphQLField

  case class User(
    @GraphQLField
    name: String,

    @GraphQLField
    age: Int
  )

  def users = Seq(
    User(
      name = "Gumby",
      age = 23
    ),
    User(
      name = "Pokey",
      age = 28
    )
  )
}

object GqlData {
  import sangria.schema._
  import sangria.macros.derive._
  import UserRepo._

  val UserType = deriveObjectType[Seq[User], User]()

  val QuerySchema = Schema(UserType)
}


object Server {
  import scala.io.StdIn
  import scala.util.Success
  import akka.actor.ActorSystem
  import akka.http.scaladsl.Http
  import akka.http.scaladsl.model._
  import akka.http.scaladsl.model.StatusCodes._
  import akka.http.scaladsl.server.Directives._
  import akka.stream.ActorMaterializer
  import sangria.parser.QueryParser
  import sangria.execution.Executor
  import sangria.ast.Document
  import sangria.marshalling.circe._
  import sangria.macros._
  import sangria.renderer.SchemaRenderer
  import sangria.schema._

  import UserRepo.User
  import UserRepo._
  import GqlData._

  def main(): Unit = {
    implicit val system = ActorSystem("my-system")
    implicit val materializer = ActorMaterializer()
    implicit val executionContext = system.dispatcher

    val route =
      get {
        complete(
          HttpEntity(ContentTypes.`text/html(UTF-8)`, "<h1>foo</h1>")
        )
      } ~
      post {

        parameter("query".as[String]) { query =>
          // val Success(q: Document) = QueryParser.parse(query)
          val q = graphql"""
          {
            name
            age
          }
          """


          println(SchemaRenderer.renderSchema(GqlData.QuerySchema))

          val f = 
            Executor.execute(
              QuerySchema,
              q,
              UserRepo.users
            ).map(OK -> _.toString)

          complete(//f
            "ok"
          )
        }
      }

    val port = 8080
    val binding = Http().bindAndHandle(route, "localhost", port)
    println(s"Server listening on port $port")
    StdIn.readLine()
    binding.flatMap(_.unbind()).onComplete(_ => system.terminate())
  }
}

Server.main()
```

**Comment by OlegIlyenko** [comment]
The key here is the way you defined `UserType`. Let's make the types explicit:

```scala
val UserType: ObjectType[Seq[User], User] = 
  deriveObjectType[Seq[User], User]()
```

`ObjectType` has 2 type parameters:

* `Ctx` (`Seq[User]` in this case) - it is an object that propagated by an execution engine to **all** types and fields in the schema
* `Val` (`User` in this case) - this is a context value which represents this type and used to resolve most of it's fields (like `name` and `age`)

When you execute a query, you need to provide both of them because you do use them both in a `UserType` which you have used as a query type. You already provide `UserRepo.users` as a `Ctx`, you just need to provide `Val` as a root value:

```scala
Executor.execute(
  QuerySchema,
  q,
  UserRepo.users,
  root = UserRepo.users.head // take the first one as an example
)
```

BTW, you don't need to use `@GraphQLField` in this setup, `deriveObjectType` automatically includes all of the fields for a case class. You only need it in for methods (which may take arguments and not part of the case class argument list).

**Comment by ckampfe** [comment]
@OlegIlyenko thank you very much, this is a terrific answer. I'm a newb at both Sangria and GraphQL itself, so this is helpful. Thanks again.
