### ISSUE TITLE
Fix infinite loop on invalid queries in OverlappingFields

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria#238]
Ref: https://github.com/graphql/graphql-js/pull/780

**Comment by sorenbs** [comment]
I could reproduce this issue by running the following query against a schema that exposes the User type:

```graphql
fragment U on User {
  ... U
}
```

This results in:

```
java.lang.StackOverflowError
    at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:112)
    at scala.collection.immutable.List.find(List.scala:84)
    at scala.collection.mutable.ListMap.get(ListMap.scala:50)
    at sangria.validation.rules.OverlappingFieldsCanBeMerged$$anon$1.getReferencedFieldsAndFragmentNames(OverlappingFieldsCanBeMerged.scala:187)
    at sangria.validation.rules.OverlappingFieldsCanBeMerged$$anon$1.sangria$validation$rules$OverlappingFieldsCanBeMerged$$anon$$collectConflictsBetweenFieldsAndFragment(OverlappingFieldsCanBeMerged.scala:358)
    at sangria.validation.rules.OverlappingFieldsCanBeMerged$$anon$1$$anonfun$sangria$validation$rules$OverlappingFieldsCanBeMerged$$anon$$collectConflictsBetweenFieldsAndFragment$1.apply(OverlappingFieldsCanBeMerged.scala:367)
    at sangria.validation.rules.OverlappingFieldsCanBeMerged$$anon$1$$anonfun$sangria$validation$rules$OverlappingFieldsCanBeMerged$$anon$$collectConflictsBetweenFieldsAndFragment$1.apply(OverlappingFieldsCanBeMerged.scala:366)
    at scala.collection.mutable.LinkedHashSet.foreach(LinkedHashSet.scala:91)
    at sangria.validation.rules.OverlappingFieldsCanBeMerged$$anon$1.sangria$validation$rules$OverlappingFieldsCanBeMerged$$anon$$collectConflictsBetweenFieldsAndFragment(OverlappingFieldsCanBeMerged.scala:366)
    at sangria.validation.rules.OverlappingFieldsCanBeMerged$$anon$1$$anonfun$sangria$validation$rules$OverlappingFieldsCanBeMerged$$anon$$collectConflictsBetweenFieldsAndFragment$1.apply(OverlappingFieldsCanBeMerged.scala:367)
[...]
```
