### ISSUE TITLE
AstSchemaMaterializer mismatch between typeDefs.length and document.definitions.length

### ISSUE THREAD

**Issue by zcourts** [sangria-graphql/sangria#326]
I'm debugging a case where I get an exception saying the schema is incomplete because a type `Permission` doesn't exist.

I know for a fact it does and that it does in fact get parsed etc properly and end up in the Schema. Debugging, I found that `AstSchemaMaterializer` exhibits some strange behaviour. The length of the `typeDefs` variable is one less than `document.definitions`.
This shouldn't be however, looking at the code:
```scala
  private lazy val typeDefs: Vector[ast.TypeDefinition] = document.definitions.collect {
    case d: ast.TypeDefinition ⇒ d
  }
```
The type it says is missing is an enum:
```graphql
enum Permission{A,B,C,ETC}
```
I can also see that it exists as an `EnumTypeDefinition` in `document.definitions`. There are other enums that successfully end up in `typeDefs` so it's not a mismatch in the above `collect` that's silently dropping it.

See screenshot below, highlighted various sections to draw attention to the key bits.

<img width="1440" alt="screen shot 2018-01-14 at 03 56 14" src="https://user-images.githubusercontent.com/692396/34912689-336286ea-f8df-11e7-85b0-adcf464cedea.png">

Scala version: `2.12.4`
Scala source and target compatibility set to `1.8`
Build tool: `Gradle`
Sangria version: `1.3.3`
JVM: Oracle JDK
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```
Mac OS High Sierra - 10.13.2 (17C205)
 
```

sangria.schema.SchemaMaterializationException: Invalid or incomplete schema, unknown type: Permission.
	at sangria.schema.AstSchemaMaterializer.$anonfun$getNamedType$8(AstSchemaMaterializer.scala:280)
	at scala.Option.getOrElse(Option.scala:121)
	at sangria.schema.AstSchemaMaterializer.$anonfun$getNamedType$2(AstSchemaMaterializer.scala:280)
	at scala.Option.getOrElse(Option.scala:121)
	at sangria.schema.AstSchemaMaterializer.$anonfun$getNamedType$1(AstSchemaMaterializer.scala:258)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at sangria.schema.AstSchemaMaterializer.getNamedType(AstSchemaMaterializer.scala:258)
	at sangria.schema.AstSchemaMaterializer.getOutputType(AstSchemaMaterializer.scala:250)
	at sangria.schema.AstSchemaMaterializer.getOutputType(AstSchemaMaterializer.scala:248)
	at sangria.schema.DefaultAstSchemaBuilder.buildFieldType(AstSchemaBuilder.scala:477)
	at tech.bloch.server.gql.SchemaBuilder.buildFieldType(SchemaBuilder.scala)
	at sangria.schema.AstSchemaMaterializer.buildField(AstSchemaMaterializer.scala:311)
	at sangria.schema.AstSchemaMaterializer.$anonfun$buildFields$5(AstSchemaMaterializer.scala:405)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at sangria.schema.AstSchemaMaterializer.buildFields(AstSchemaMaterializer.scala:405)
	at sangria.schema.AstSchemaMaterializer.$anonfun$buildInterfaceDef$2(AstSchemaMaterializer.scala:352)
	at sangria.schema.Named$.$anonfun$checkIntFields$1(Schema.scala:117)
	at sangria.schema.ObjectLikeType.ownFields(Schema.scala:180)
	at sangria.schema.ObjectLikeType.ownFields$(Schema.scala:180)
	at sangria.schema.InterfaceType.ownFields$lzycompute(Schema.scala:253)
	at sangria.schema.InterfaceType.ownFields(Schema.scala:253)
	at sangria.schema.ObjectLikeType.fields(Schema.scala:191)
	at sangria.schema.ObjectLikeType.fields$(Schema.scala:191)
	at sangria.schema.InterfaceType.fields$lzycompute(Schema.scala:253)
	at sangria.schema.InterfaceType.fields(Schema.scala:253)
	at sangria.schema.Schema.collectTypes$1(Schema.scala:817)
	at sangria.schema.Schema.$anonfun$types$2(Schema.scala:819)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at sangria.schema.Schema.collectTypes$1(Schema.scala:817)
	at sangria.schema.Schema.$anonfun$types$2(Schema.scala:819)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at sangria.schema.Schema.collectTypes$1(Schema.scala:817)
	at sangria.schema.Schema.$anonfun$types$2(Schema.scala:819)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at sangria.schema.Schema.collectTypes$1(Schema.scala:817)
	at sangria.schema.Schema.$anonfun$types$8(Schema.scala:846)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at sangria.schema.Schema.types$lzycompute(Schema.scala:846)
	at sangria.schema.Schema.types(Schema.scala:773)
	at sangria.schema.Schema.inputTypes$lzycompute(Schema.scala:857)
	at sangria.schema.Schema.inputTypes(Schema.scala:857)
	at sangria.schema.DefaultValuesValidationRule.validate(SchemaValidationRule.scala:43)
	at sangria.schema.Schema.$anonfun$validationErrors$1(Schema.scala:910)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at sangria.schema.Schema.<init>(Schema.scala:910)
	at tech.bloch.server.gql.SchemaBuilder.buildSchema(SchemaBuilder.scala:67)
	at sangria.schema.AstSchemaMaterializer.build$lzycompute(AstSchemaMaterializer.scala:85)
	at sangria.schema.AstSchemaMaterializer.build(AstSchemaMaterializer.scala:69)
	at sangria.schema.AstSchemaMaterializer$.buildSchema(AstSchemaMaterializer.scala:512)
	at sangria.schema.Schema$.buildFromAst(Schema.scala:966)
	at tech.bloch.server.gql.SchemaUtils.$anonfun$load$13(SchemaUtils.scala:78)
	at scala.util.Try$.apply(Try.scala:209)
	at tech.bloch.server.gql.SchemaUtils.$anonfun$load$12(SchemaUtils.scala:78)
	at tech.bloch.server.gql.package$CanMapTo.mapTo(gql.scala:39)
	at tech.bloch.server.gql.SchemaUtils.load(SchemaUtils.scala:76)
	at tech.bloch.server.gql.GQLHandler.process(GQLHandler.scala:52)
	at tech.bloch.server.controller.GraphQLController.graphql(GraphQLController.scala:31)
	at tech.bloch.server.controller.GraphQLController$$FastClassBySpringCGLIB$$7ea83c82.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport$CompletableFutureDelegate$1.get(AsyncExecutionAspectSupport.java:328)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by zcourts** [comment]
ok, changing `Permission ` to `PermissionVal` and it works as expected...

**Comment by zcourts** [comment]
Stupid, ignore. The `type` def. had a typo. `Permission` was `Permision`.
