### ISSUE TITLE
Does enum input types support default values ?

### ISSUE THREAD

**Issue by MdSarfarazKhan** [sangria-graphql/sangria#422]
I'm trying to execute an introspection query against a schema having optional Enum input and a default value for it and getting Exception at run time.
Below is a sample code

```
sealed abstract class Weekday(val order: Int) extends EnumEntry with Ordered[Weekday] {
  def compare(that: Weekday) = this.order - that.order
}

object Weekday extends Enum[Weekday] {
  val values = findValues

  case object Monday extends Weekday(2)
  case object Tuesday extends Weekday(3)
  case object Wednesday extends Weekday(4)
  case object Thursday extends Weekday(5)
  case object Friday extends Weekday(6)
  case object Saturday extends Weekday(7)
  case object Sunday extends Weekday(1)
}

case class WeekDayContainer(weekDay: Weekday)

object WeekDayContainer{
  val default =  WeekDayContainer(Weekday.Monday)
}
//Input Object
case class Context(id: Int, name: String, weekDayContainer: WeekDayContainer = WeekDayContainer.default)

//Macro derivation
implicit val WeekdayInputType: EnumType[Weekday] = deriveEnumType[Weekday](
    EnumTypeName("Weekday")
)

implicit val WeekContInputType: InputObjectType[WeekDayContainer] = deriveInputObjectType[WeekDayContainer]()

implicit val pcInputType: InputObjectType[Context] = deriveInputObjectType[Context]()

val contextArg = Argument("Context", pcInputType, description = "context of the xyz")

```
Below is the stacktrace 

```
Invalid default value of field 'weekDayContainer' in input type 'Context'. Field 'Context.weekDayContainer.weekDay' has wrong value: Enum value expected.
        at sangria.schema.SchemaValidationRule$.validateWithException(SchemaValidationRule.scala:41)
        at sangria.schema.Schema.<init>(Schema.scala:918)
        at SchemaDefinition$.<init>(SchemaDefinition.scala:215)
        at SchemaDefinition$.<clinit>(SchemaDefinition.scala)
        ... 111 more



Caused by: sangria.schema.SchemaValidationException: Schema does not pass validation. Violations:

Invalid default value of field 'weekDayContainer' in input type 'Context'. Field 'Context.weekDayContainer.weekDay' has wrong value: Enum value expected.
        at sangria.schema.SchemaValidationRule$.validateWithException(SchemaValidationRule.scala:41)
        at sangria.schema.Schema.<init>(Schema.scala:918)
        at SchemaDefinition$.<init>(SchemaDefinition.scala:215)
        at SchemaDefinition$.<clinit>(SchemaDefinition.scala)
        ... 111 more
```

**Comment by MdSarfarazKhan** [comment]
After adding a Decoder it works fine
`
 private val stringEncoder = implicitly[Encoder[String]]
  private val stringDecoder = implicitly[Decoder[String]]

  implicit val ChargeTypeEncoder: Encoder[Weekday] = new Encoder[Weekday] {
    override def apply(enum: Weekday): Json = stringEncoder.apply(enum.entryName)
  }

  implicit val ChargeTypeDecoder: Decoder[Weekday] = new Decoder[Weekday] {
    final def apply(c: HCursor): Result[Weekday] = stringDecoder.apply(c).flatMap { s =>
      val maybeMember = Weekday.withNameOption(s)
      maybeMember match {
        case Some(member) => Right(member)
        case _ =>
          Left(DecodingFailure(s"$s' is not a member of enum $Weekday", c.history))
      }
    }
  }
`

**Comment by ASchmidt84** [comment]
Which decode or encoder? I have the same issue

**Comment by PAStheLoD** [comment]
@ASchmidt84, the comment from 2018 uses Sangria Circe, you might find this useful https://github.com/sangria-graphql/sangria-circe/issues/13#issuecomment-406703668 (Are you at least a bit familiar with how these implicit converters work in Scala?)

**Comment by ASchmidt84** [comment]
@PAStheLoD hi, it seemes like not :)
I have a problem and get always an error:
```
{
    "data": null,
    "errors": [
        {
            "message": "Argument 'manager' has invalid value: At path '/role./FulfillerArticleManagerRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role./UserRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role./FulfillerPresidentRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role./SystemRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role./FulfillerInvoiceManagerRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role./AdminRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role./SuperAdminRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role': error.sealed.trait (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role./FulfillerCEOManagerRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        },
        {
            "message": "Argument 'manager' has invalid value: At path '/role./AtheneRole': error.path.missing (line 2, column 55):\n    addManager (vendorNumber: $vendorNumber, manager: $manager) {\n                                                      ^",
            "path": [
                "addManager"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 55
                }
            ]
        }
    ]
}
```
The mutation take an argument Manager. The Manager case class has an Enum (by enumeratum) with name role.
Here are my Enum Implementation.
```
sealed abstract class DefaultRoles private[adt](@GraphQLDescription("the name of the role") val name: String) extends EnumEntry {
  override def toString: String = name.trim.toLowerCase
}

object DefaultRoles extends Enum[DefaultRoles] {

  import sangria.marshalling.circe._

  override def values: IndexedSeq[DefaultRoles] = findValues

  case object SystemRole extends DefaultRoles("system")
  case object SuperAdminRole extends DefaultRoles("super-admin")
  case object AdminRole extends DefaultRoles("admin")
  case object AtheneRole extends DefaultRoles("athene")
  case object FulfillerPresidentRole extends DefaultRoles("fulfiller-president")
  case object FulfillerCEOManagerRole extends DefaultRoles("fulfiller-ceo-manager")
  case object FulfillerArticleManagerRole extends DefaultRoles("fulfiller-article-manager")
  case object FulfillerInvoiceManagerRole extends DefaultRoles("fulfiller-invoice-manager")
  case object UserRole extends DefaultRoles("user")

  implicit val format: OFormat[DefaultRoles] = derived.oformat[DefaultRoles]()

//  implicit val DefaultRolesType = deriveEnumType[DefaultRoles](
//    EnumTypeName("RolesEnum"),
//    EnumTypeDescription("A enum role type. Describes which role a user has or must have.")
//  )

  implicit val DefaultRolesType = EnumType(
    name = "DefaultRoles",
    description = Some("A enum role type. Describes a special role"),
    values = List(
      EnumValue(
        name = "FulfillerPresidentRole",
        description = Some("Fulfiller president role - means owner of the fulfiller"),
        value = FulfillerPresidentRole
      ),
      EnumValue(
        name = "FulfillerCEOManagerRole",
        description = Some("Fulfiller CEO role"),
        value = FulfillerCEOManagerRole
      ),
      EnumValue(
        name = "FulfillerArticleManagerRole",
        description = Some("Fulfiller article manager role - only responsible for articles of the fulfiller"),
        value = FulfillerArticleManagerRole
      ),
      EnumValue(
        name = "FulfillerInvoiceManagerRole",
        description = Some("Fulfiller invoice manager role - only responsible for invoice and all relating topics"),
        value = FulfillerInvoiceManagerRole
      ),
      EnumValue(
        name = "UserRole",
        description = Some("Simple user role"),
        value = UserRole
      )
    )
  )

//  implicit val DefaultRolesInputType = deriveInputObjectType[DefaultRoles]()

  private val stringEncoder = implicitly[Encoder[String]]
  private val stringDecoder = implicitly[Decoder[String]]

  implicit val ChargeTypeEncoder: Encoder[DefaultRoles] = new Encoder[DefaultRoles] {
    override def apply(enum: DefaultRoles): Json = stringEncoder.apply(enum.entryName)
  }

  implicit val ChargeTypeDecoder: Decoder[DefaultRoles] = new Decoder[DefaultRoles] {
    final def apply(c: HCursor): Result[DefaultRoles] = stringDecoder.apply(c).flatMap { s =>
      val maybeMember = DefaultRoles.withNameOption(s)
      maybeMember match {
        case Some(member) => Right(member)
        case _ => Left(DecodingFailure(s"$s' is not a member of enum $DefaultRolesType", c.history))
      }
    }
  }

}
```

The problem is I did it manual, I did it with dervied and nothing work.
Do you have an idea where I did the error?
Thank you
