### ISSUE TITLE
scala.collection.immutable.Vector cannot be cast to spray.json.JsValue

### ISSUE THREAD

**Issue by vasekboch** [sangria-graphql/sangria#449]
Hi, I've been strugling with this last year, but I managed to somehow make it work. But now in this example it does not work.

AFAIK there is nothing special about this usage of graphql mutation. But It seems that its only me with this issue.
```
    "org.sangria-graphql" %% "sangria" % "1.4.2",
    "org.sangria-graphql" %% "sangria-spray-json" % "1.0.1",
```

```scala
import sangria.schema._
import sangria.execution._
import sangria.marshalling.sprayJson._
import sangria.parser.QueryParser
import spray.json._
import scala.concurrent.duration._
import scala.concurrent.Await
import scala.concurrent.ExecutionContext.Implicits.global
import sangria.macros.derive.deriveInputObjectType

case class Ctx()
case class ContactInput(name: String)

object MyJsonProtocol extends DefaultJsonProtocol {
  implicit val contactInput: RootJsonFormat[ContactInput] = jsonFormat1(ContactInput.apply)
}

import MyJsonProtocol._

// The schema

val ContactInputType: InputType[ContactInput] = deriveInputObjectType[ContactInput]()

val submit: Field[Ctx, Unit] = Field("submit", StringType,
  arguments = Argument("contacts", ListInputType(ContactInputType)) :: Nil,
  resolve = c => "hello" + c.arg("contacts")
)

// Schema root
val Mutation: ObjectType[Ctx, Unit] = ObjectType("Mutation", fields[Ctx, Unit](submit))
val Query: ObjectType[Ctx, Unit] = ObjectType("Query", fields[Ctx, Unit](
  Field("hello", StringType, resolve = _ ⇒ "Hello world!")
))
val schema = Schema(Query, Some(Mutation))

// Test mutation
val query = """
  mutation {submit(contacts:[{name: "Test"}])}
"""

val result = Executor.execute(
  schema,
  QueryParser.parse(query).get,
  userContext = Ctx(),
)
println(Await.result(result, 10.seconds))

// Expected output:
//
//   {
//     "submit": "helloVector(...."
//   }

// Actual output:
// 
// java.lang.ClassCastException: scala.collection.immutable.Vector cannot be cast to spray.json.JsValue
//	at sangria.marshalling.sprayJson$$anon$2.fromResult(scratch.scala:99)
//	at sangria.execution.ValueCollector$.$anonfun$getArgumentValues$6(scratch.scala:86)
```

**Comment by jkenny** [comment]
@vasekboch did you ever find a solution for this? I'm encountering the exact same error and cannot figure out what the problem is. I have lots of mutations that take arrays of inputs and work fine, but for some reason in one instance I get this exception.

**Comment by jkenny** [comment]
For anybody who comes across this nightmare issue in the future, the fix is to make sure the return type of `deriveInputObjectType` is `InputObjectType` rather than `InputType`. I.e. In @vasekboch 's code above, it should be ```val ContactInputType: InputObjectType[ContactInput] = deriveInputObjectType[ContactInput]()```

**Comment by nickhudkins** [comment]
@vasekboch as @jkenny said, it appears that the type annotation was incorrect causing your issue. You can either annotate with `InputObjectType[ContactInput]` or forego the annotation:
`val ContactInputType = deriveInputObjectType[ContactInput]()`
and you'll be set.

**Comment by muuki88** [comment]
I wanted to add some more cases where this can happen and how to make sangria happy again

## `Seq[T]` types

This throws a class cast exception

```scala
val labels: Argument[Seq[String]] = Argument[Seq[String]](
  name = "labels",
  argumentType = ListInputType(StringType)
)
```

and can be fixed by add `@@ FromInput.CoercedScalaResult`

```scala
val labels: Argument[Seq[String @@ FromInput.CoercedScalaResult]] = Argument(
  name = "labels",
  argumentType = ListInputType(StringType)
)
```

## Complex types

Same for complex types. You need to add `@@ FromInput.InputObjectResult`

```scala
case class User(id: Int)
val users: Argument[Seq[User @@ FromInput.InputObjectResult]] =  Argument(
  name = "users",
  argumentType = ListInputType(UserType),
) 
```
