### ISSUE TITLE
Long string 2 bytes error

### ISSUE THREAD

**Issue by angelorobo** [sangria-graphql/sangria#455]
We're trying to send a long text like HTML content to GraphQL field. But we are getting string size limit 2bytes error. If it exceeds 2bytes, the request won't be parsed. How can we make this work? Or we have to switch back to REST API to accept long string/text processing?

**Comment by tarangbhalodia** [comment]
I have the same issue. I have a graphql mutation which accepts `StringType`. Here's the stack trace:
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MatchError: 413 (of class java.lang.Integer)]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:323)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:243)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:382)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:380)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: scala.MatchError: 413 (of class java.lang.Integer)
	at controllers.ErrorHandler.onClientError(ErrorHandler.scala:35)
	at play.api.mvc.PlayBodyParsers.$anonfun$createBadResult$1(BodyParsers.scala:917)
	at play.api.mvc.PlayBodyParsers.$anonfun$enforceMaxLength$3(BodyParsers.scala:930)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
```

When I try to print the same string using a simple Java main program, I get below error:
```
java: constant string too long
```

**Comment by schrepfler** [comment]
I think there’s a limit to how big an declared String instance can be when done in code. Try to load it from an external resource (like a file). I get the feeling you’re not testing the same thing which is triggering the original exception.

**Comment by nickhudkins** [comment]
Hi @angelorobo and @tarangbhalodia this stack trace would indicate that Play's BodyParser is throwing the error from `enforceMaxLength` in Play's Body Parser.

Best of luck!
